### ISSUE TITLE
Packages of libwww 5.4.1 are not available.

### ISSUE THREAD

**Issue by dbaio** [w3c/libwww#3]
Packages of libwww 5.4.1 are not available.

https://www.w3.org/Library/ --> 
October 21 2005: Packaging of the libwww 5.4.1 release. This maintenance release fixes some SSL issues, brings the configure scripts up to date and fixes a security vulnerability in HTBound.c

https://www.w3.org/Library/Distribution/

**Comment by jkbzh** [comment]
Hello @dbaio ,

I don't think we ever got to package 5.4.1. However, you can get it directly from git and bootstrap it. I update the autotools setup to make sure it can be compiled (at least under Debian). Libwww is community maintained since some years ago and that seems to have stopped too. There are other modern libraries you can use instead. Cheers.

**Comment by dbaio** [comment]
Thank you
